### ISSUE TITLE
Use pure ESM package in Main-process, such as execa, node-fetch  | 在主进程引入 execa、node-fetch 这类纯ESM 包

### ISSUE THREAD

**Issue by Matrix53** [caoxiemeihao/electron-vite-vue#65]
该问题可能有关 **Vite** 本身，具体来说，我想在**主进程**中使用[execa](https://www.npmjs.com/package/execa)这个库，但该库不支持`require`，只支持`import`或者`dynamic import`。

- 当`execa`作为`devDependencies`时
  - 无论使用`import`还是`dynamic import`，`npm run dev`报错如下，程序无法启动：

    ![image](https://user-images.githubusercontent.com/55696968/155991241-971f517b-8f21-4bc8-8e7a-c3c6f22fdde4.png)

- 当`execa`作为`dependencies`时
  - 若使用`import`，则`import`会被编译成`require`，执行时报错
  - 而`dynamic import`会被编译成如下语句：

    ![image](https://user-images.githubusercontent.com/55696968/155992442-e5702bd2-0022-4c72-a1a9-29e51a8acd1a.png)
    仍然在执行时报错：

    ![image](https://user-images.githubusercontent.com/55696968/155992600-83524c35-86ac-4815-b2ec-ad58ad51385c.png)

我的项目结构如下，其中，`index.ts`引入了`utils.ts`，而我想在`utils.ts`中引入`execa`：

- main
  - index.ts
  - utils.ts
- preload
- renderer

另外，我的 **Vite** 版本为2.8.4，Electron版本为17.1.0，execa版本为6.1.0，均为打开本issue时的最新稳定版本，模板中的 **Vite** 配置文件我均未修改

**Comment by caoxiemeihao** [comment]
拉下最新代码即可，现在已经支持 execa、node-fetch 这种纯 ESM 包了 🎉
有兴趣可以研究下这个文件 😄
https://github.com/caoxiemeihao/vite-react-electron/blob/main/scripts/vite-plugin-esm2cjs.ts

**Comment by oceanlvr** [comment]
> 这里需要解释下 Electron 不支持 ESModule；现在 npm 社区有一部分包很激进，直接用的 ESModule 格式 😅 可是我们项目用的是 CommonsJs 格式，所以这里需要提前将 ESModule 转换成 CommonsJs 🥺 当下我另一个模板 [vite-react-electron](https://github.com/caoxiemeihao/vite-react-electron) 已经实现该需求，可以支持类似 [execa](https://www.npmjs.com/package/execa)、[node-fetch](https://www.npmjs.com/package/node-fetch) 这中纯 ESModule 格式的包 🎉
> 
> 使用方式可以参考 👉 [vite-react-electron](https://github.com/caoxiemeihao/vite-react-electron) 研究原理可以参考 👉 [vite-plugin-esm2cjs.ts](https://github.com/caoxiemeihao/vite-react-electron/blob/main/scripts/vite-plugin-esm2cjs.ts)

草鞋老师，请问这个实现就是 vite-plugin-esmodule 插件吗？
