### ISSUE TITLE
[Help] 请教下使用vue-router打包后出现exports is not defined报错

### ISSUE THREAD

**Issue by zqy233** [caoxiemeihao/electron-vite-vue#94]
开发环境是可以正常使用vue-router的，但打包后electron控制台出现Uncaught ReferenceError: exports is not defined报错，找了下是vue-router源码里面开头代码的问题Object.defineProperty(exports, '__esModule', { value: true });，请教下大佬遇到过这种情况嘛？

The vue-router can be used normally in the development environment, but after build, "uncaught referenceerror: exports is not defined error" appears on the electron‘s console. It is the problem of the beginning code in the vue-router source code "Object.defineProperty(exports, '__esModule', { value: true });，", Excuse me, have you ever encountered such a situation?

**Comment by zqy233** [comment]
vite.config.ts中加入以下代码，成功编译了
`rollupOptions: {
      output: {
        format: "commonjs"
      }
    }`

**Comment by Davidzhu001** [comment]
@zqy233 我准备加了好像没用，请问能分享下吗

**Comment by caoxiemeihao** [comment]
> @zqy233 我准备加了好像没用，请问能分享下吗

去看这个 issues 👉 https://github.com/electron-vite/electron-vite-vue/issues/103#issuecomment-1098662928

**Comment by zqy233** [comment]
> @zqy233 我准备加了好像没用，请问能分享下吗
就是加了这个啊，router使用createWebHashHistory试试
 build: {
    sourcemap: true,
    outDir: "../../dist/renderer",
    rollupOptions: {
      output: {
        format: "cjs"
      }
    }
  },

**Comment by zqy233** [comment]
> @zqy233 我准备加了好像没用，请问能分享下吗
router使用createWebHashHistory试试
`build: {
sourcemap: true,
outDir: "../../dist/renderer",
rollupOptions: {
output: {
format: "cjs"
}
}
},`

**Comment by zqy233** [comment]
这里给一下官方给的解决方案，需要0.4.2版本及以上 
vite.config.ts

```ts
import polyfillExports from 'vite-plugin-electron/polyfill-exports'

export default {
  plugins: [
    // ...other plugins
    polyfillExports(),
  ],
}
```

##
